import { posix } from 'node:path';
import type { FileCategory, FileTag, Language, SkipReason } from './types';

const VENDOR_DIRS = new Set([
  'node_modules', 'bower_components', 'vendor', 'dist', 'build', 'out', '.next', '.nuxt', '.svelte-kit', '.turbo',
  '.cache', 'coverage', '__pycache__', '.venv', 'venv', 'site-packages', '.git', '.pytest_cache', '.mypy_cache', '.tox',
]);

const LOCKFILES = new Set([
  'package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock', 'pnpm-lock.yaml', 'poetry.lock', 'Pipfile.lock', 'uv.lock',
]);

const BINARY_EXT = new Set([
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'tif', 'tiff', 'avif', 'pdf', 'zip', 'gz', 'tgz', 'bz2', 'xz', '7z', 'rar',
  'jar', 'war', 'class', 'so', 'dll', 'dylib', 'exe', 'bin', 'o', 'a', 'wasm', 'woff', 'woff2', 'ttf', 'otf', 'eot',
  'mp3', 'mp4', 'mov', 'avi', 'webm', 'ogg', 'wav', 'flac', 'psd', 'sketch', 'sqlite', 'db', 'pyc', 'pyo', 'node', 'lockb',
]);

const EXT_LANGUAGE: Record<string, Language> = {
  ts: 'typescript', tsx: 'typescript', mts: 'typescript', cts: 'typescript',
  js: 'javascript', jsx: 'javascript', mjs: 'javascript', cjs: 'javascript',
  py: 'python', json: 'json', jsonc: 'json', yml: 'yaml', yaml: 'yaml', toml: 'toml', sql: 'sql',
  sh: 'shell', bash: 'shell', zsh: 'shell', html: 'html', htm: 'html', css: 'css', scss: 'css',
  md: 'markdown', mdx: 'markdown', xml: 'xml',
};

const CONFIG_LANGUAGES = new Set<Language>(['json', 'yaml', 'toml', 'sql', 'shell', 'dockerfile', 'env', 'xml']);
const GENERATED_RE = /@generated|DO NOT EDIT|Code generated by|auto-?generated/i;
const MINIFIABLE_EXT = new Set(['js', 'mjs', 'cjs', 'css']);

const extOf = (path: string) => {
  const base = posix.basename(path);
  const dot = base.lastIndexOf('.');
  return dot > 0 ? base.slice(dot + 1).toLowerCase() : '';
};

export function isLockfile(path: string): boolean {
  const base = posix.basename(path);
  return LOCKFILES.has(base) || /^requirements.*\.txt$/i.test(base);
}

export function languageOf(path: string): Language {
  const base = posix.basename(path);
  if (/^Dockerfile(\..+)?$/i.test(base) || base.toLowerCase().endsWith('.dockerfile')) return 'dockerfile';
  if (base === '.env' || base.startsWith('.env.')) return 'env';
  return EXT_LANGUAGE[extOf(path)] ?? 'other';
}

export function categoryOf(path: string, language: Language): FileCategory {
  if (isLockfile(path)) return 'lockfile';
  if (language === 'typescript' || language === 'javascript' || language === 'python') return 'source';
  if (CONFIG_LANGUAGES.has(language) || ['Makefile', 'Procfile', '.npmrc', '.htaccess'].includes(posix.basename(path))) return 'config';
  if (language === 'markdown' || ['txt', 'rst'].includes(extOf(path))) return 'doc';
  return 'other';
}

export function tagsOf(path: string): FileTag[] {
  const tags: FileTag[] = [];
  if (/(^|\/)(tests?|__tests__|__mocks__|spec|fixtures)\//i.test(path)
    || /\.(test|spec)\.[cm]?[jt]sx?$/i.test(path)
    || /(^|\/)test_[^/]*\.py$|_test\.py$/i.test(path)) tags.push('test');
  if (/(^|\/)(examples?|samples?|demos?)\//i.test(path)) tags.push('example');
  if (/^\.github\/workflows\/|^\.circleci\/|(^|\/)\.gitlab-ci\.ya?ml$/.test(path)) tags.push('ci');
  if (/(^|\/)(Dockerfile[^/]*|docker-compose[^/]*\.ya?ml|[^/]+\.tf)$|(^|\/)(terraform|k8s|kubernetes|helm|infra)\//i.test(path)) tags.push('infra');
  return tags;
}

/** Decides from the tree entry alone (no file read). */
export function skipReasonForPath(path: string, mode: string, type: string): SkipReason | null {
  if (type === 'commit') return 'submodule';
  if (mode === '120000') return 'symlink';
  if (path.split('/').slice(0, -1).some((segment) => VENDOR_DIRS.has(segment))) return 'vendor';
  if (BINARY_EXT.has(extOf(path))) return 'binary';
  if (/\.min\.(js|css)$/i.test(path)) return 'minified';
  return null;
}

/** Decides from size and the first bytes of the file (`head`, up to ~8 KB). */
export function skipReasonForContent(path: string, size: number, head: Buffer, maxFileBytes: number): SkipReason | null {
  if (isLockfile(path)) return null;
  if (size > maxFileBytes) return 'too_large';
  if (head.includes(0)) return 'binary';
  const text = head.toString('utf8');
  if (MINIFIABLE_EXT.has(extOf(path)) && text.length >= 2_000) {
    const lines = text.split('\n');
    if (text.length / lines.length > 300) return 'minified';
  }
  if (GENERATED_RE.test(text.split('\n', 5).join('\n'))) return 'generated';
  return null;
}
