import { posix } from 'node:path';
import type { FileCategory, FileTag, Language, SkipReason } from './types';

// Skipped as vendor regardless of where they appear in the path.
const ALWAYS_VENDOR_DIRS = new Set([
  'node_modules', 'bower_components', 'site-packages', '__pycache__', '.venv', 'venv',
  '.next', '.nuxt', '.svelte-kit', '.turbo', '.git', '.pytest_cache', '.mypy_cache', '.tox',
]);

// Skipped as vendor only at a project root (first segment, or a monorepo package root below) — these
// names are also common for first-party directories deeper in a tree (e.g. src/api/vendor/dashboard.ts).
const CONTEXTUAL_VENDOR_DIRS = new Set(['vendor', 'dist', 'build', 'out', '.cache', 'coverage']);
const MONOREPO_ROOTS = new Set(['apps', 'packages', 'services', 'libs', 'modules']);

function isVendorSegment(segments: readonly string[], index: number): boolean {
  const segment = segments[index] ?? '';
  if (ALWAYS_VENDOR_DIRS.has(segment)) return true;
  if (!CONTEXTUAL_VENDOR_DIRS.has(segment)) return false;
  // First path segment, or directly under <monorepoRoot>/<pkg>/.
  return index === 0 || (index === 2 && MONOREPO_ROOTS.has(segments[0] ?? ''));
}

const LOCKFILES = new Set([
  'package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock', 'pnpm-lock.yaml', 'poetry.lock', 'Pipfile.lock', 'uv.lock',
]);

const BINARY_EXT = new Set([
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'tif', 'tiff', 'avif', 'pdf', 'zip', 'gz', 'tgz', 'bz2', 'xz', '7z', 'rar',
  'jar', 'war', 'class', 'so', 'dll', 'dylib', 'exe', 'bin', 'o', 'a', 'wasm', 'woff', 'woff2', 'ttf', 'otf', 'eot',
  'mp3', 'mp4', 'mov', 'avi', 'webm', 'ogg', 'wav', 'flac', 'psd', 'sketch', 'sqlite', 'db', 'pyc', 'pyo', 'node', 'lockb',
]);

const EXT_LANGUAGE: Record<string, Language> = {
  ts: 'typescript', tsx: 'typescript', mts: 'typescript', cts: 'typescript',
  js: 'javascript', jsx: 'javascript', mjs: 'javascript', cjs: 'javascript',
  py: 'python', json: 'json', jsonc: 'json', yml: 'yaml', yaml: 'yaml', toml: 'toml', sql: 'sql',
  sh: 'shell', bash: 'shell', zsh: 'shell', html: 'html', htm: 'html', css: 'css', scss: 'css',
  md: 'markdown', mdx: 'markdown', xml: 'xml',
};

const CONFIG_LANGUAGES = new Set<Language>(['json', 'yaml', 'toml', 'sql', 'shell', 'dockerfile', 'env', 'xml']);
const MINIFIABLE_EXT = new Set(['js', 'mjs', 'cjs', 'css']);

// A line must look like a comment before its content is checked for a generated-file marker, so
// prose that merely discusses editing (e.g. "// Do not edit this list manually") isn't misread as one.
const COMMENT_MARKER_RE = /^\s*(\/\/|\/\*|#|\*|<!--|--)/;

function isGeneratedMarkerLine(line: string): boolean {
  if (!COMMENT_MARKER_RE.test(line)) return false;
  return /@generated/i.test(line)
    || /DO NOT EDIT/.test(line)
    || /Code generated by/.test(line)
    || /auto-?generated file/i.test(line)
    || /this file (?:is|was) auto-?generated/i.test(line);
}

const extOf = (path: string) => {
  const base = posix.basename(path);
  const dot = base.lastIndexOf('.');
  return dot > 0 ? base.slice(dot + 1).toLowerCase() : '';
};

/** Exact set of machine-generated lockfiles exempt from size/binary/generated/minified checks entirely. */
export function isMachineLockfile(path: string): boolean {
  return LOCKFILES.has(posix.basename(path));
}

export function isLockfile(path: string): boolean {
  const base = posix.basename(path);
  return LOCKFILES.has(base) || /^requirements.*\.txt$/i.test(base);
}

export function languageOf(path: string): Language {
  const base = posix.basename(path);
  if (/^Dockerfile(\..+)?$/i.test(base) || base.toLowerCase().endsWith('.dockerfile')) return 'dockerfile';
  if (base === '.env' || base.startsWith('.env.')) return 'env';
  return EXT_LANGUAGE[extOf(path)] ?? 'other';
}

export function categoryOf(path: string, language: Language): FileCategory {
  if (isLockfile(path)) return 'lockfile';
  if (language === 'typescript' || language === 'javascript' || language === 'python') return 'source';
  if (CONFIG_LANGUAGES.has(language) || ['Makefile', 'Procfile', '.npmrc', '.htaccess'].includes(posix.basename(path))) return 'config';
  if (language === 'markdown' || ['txt', 'rst'].includes(extOf(path))) return 'doc';
  return 'other';
}

export function tagsOf(path: string): FileTag[] {
  const tags: FileTag[] = [];
  if (/(^|\/)(tests?|__tests__|__mocks__|spec|fixtures)\//i.test(path)
    || /\.(test|spec)\.[cm]?[jt]sx?$/i.test(path)
    || /(^|\/)test_[^/]*\.py$|_test\.py$/i.test(path)) tags.push('test');
  if (/(^|\/)(examples?|samples?|demos?)\//i.test(path)) tags.push('example');
  if (/^\.github\/workflows\/|^\.circleci\/|(^|\/)\.gitlab-ci\.ya?ml$/.test(path)) tags.push('ci');
  if (/(^|\/)(Dockerfile[^/]*|docker-compose[^/]*\.ya?ml|[^/]+\.tf)$|(^|\/)(terraform|k8s|kubernetes|helm|infra)\//i.test(path)) tags.push('infra');
  return tags;
}

/** Decides from the tree entry alone (no file read). */
export function skipReasonForPath(path: string, mode: string, type: string): SkipReason | null {
  if (type === 'commit') return 'submodule';
  if (mode === '120000') return 'symlink';
  const ancestors = path.split('/').slice(0, -1);
  if (ancestors.some((_, index) => isVendorSegment(ancestors, index))) return 'vendor';
  if (BINARY_EXT.has(extOf(path))) return 'binary';
  if (/\.min\.(js|css)$/i.test(path)) return 'minified';
  return null;
}

/** Decides from size and the first bytes of the file (`head`, up to ~8 KB). */
export function skipReasonForContent(path: string, size: number, head: Buffer, maxFileBytes: number): SkipReason | null {
  if (isMachineLockfile(path)) return null;
  if (size > maxFileBytes) return 'too_large';
  if (head.includes(0)) return 'binary';
  // requirements*.txt is a lockfile by category but isn't machine-generated the way LOCKFILES are:
  // it still goes through the too_large/binary checks above, but is exempt from generated/minified below.
  if (isLockfile(path)) return null;
  const text = head.toString('utf8');
  if (MINIFIABLE_EXT.has(extOf(path)) && text.length >= 2_000) {
    const lines = text.split('\n');
    if (text.length / lines.length > 300) return 'minified';
  }
  if (text.split('\n').slice(0, 5).some(isGeneratedMarkerLine)) return 'generated';
  return null;
}
