export const ERROR_CODES = [
  'VALIDATION', 'NOT_FOUND', 'NOT_READY', 'CONFLICT', 'QUEUE_FULL', 'RATE_LIMITED',
  'REPO_NOT_FOUND', 'AUTH_REQUIRED', 'AUTH_INVALID', 'REF_NOT_FOUND', 'REPO_TOO_LARGE', 'CLONE_TIMEOUT',
  'GITHUB_RATE_LIMITED', 'LLM_UNAVAILABLE', 'LLM_REFUSAL', 'LLM_OUTPUT_INVALID',
  'SANDBOX_UNAVAILABLE', 'SANDBOX_TIMEOUT', 'SANDBOX_OOM', 'OSV_UNAVAILABLE',
  'BUDGET_EXHAUSTED', 'SCAN_DEADLINE', 'CANCELLED', 'INTERNAL', 'ALL_ANALYZERS_FAILED',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];
