import { describe, expect, it } from 'vitest';
import { categoryOf, languageOf, skipReasonForContent, skipReasonForPath, tagsOf } from '../src/index/classify';

const MB = 1024 * 1024;

describe('languageOf', () => {
  it.each([
    ['src/a.ts', 'typescript'], ['src/a.tsx', 'typescript'], ['lib/x.mjs', 'javascript'], ['app.py', 'python'],
    ['Dockerfile', 'dockerfile'], ['docker/Dockerfile.prod', 'dockerfile'], ['.env.example', 'env'],
    ['config.yml', 'yaml'], ['db/001.sql', 'sql'], ['README.md', 'markdown'], ['logo.png', 'other'],
  ])('%s → %s', (path, lang) => expect(languageOf(path)).toBe(lang));
});

describe('categoryOf', () => {
  it.each([
    ['package-lock.json', 'lockfile'], ['apps/web/pnpm-lock.yaml', 'lockfile'], ['poetry.lock', 'lockfile'],
    ['requirements.txt', 'lockfile'], ['requirements-dev.txt', 'lockfile'],
    ['src/a.ts', 'source'], ['main.py', 'source'], ['package.json', 'config'], ['.github/workflows/ci.yml', 'config'],
    ['Dockerfile', 'config'], ['docs/guide.md', 'doc'], ['notes.txt', 'doc'], ['logo.png', 'other'],
  ])('%s → %s', (path, cat) => expect(categoryOf(path, languageOf(path))).toBe(cat));
});

describe('tagsOf', () => {
  it('detects tests, examples, CI and infra', () => {
    expect(tagsOf('src/__tests__/a.ts')).toContain('test');
    expect(tagsOf('src/a.spec.ts')).toContain('test');
    expect(tagsOf('tests/test_api.py')).toContain('test');
    expect(tagsOf('pkg/api_test.py')).toContain('test');
    expect(tagsOf('examples/basic/index.js')).toContain('example');
    expect(tagsOf('.github/workflows/ci.yml')).toContain('ci');
    expect(tagsOf('infra/main.tf')).toContain('infra');
    expect(tagsOf('docker-compose.yml')).toContain('infra');
    expect(tagsOf('src/server/index.ts')).toEqual([]);
  });
});

describe('skipReasonForPath', () => {
  it.each([
    ['node_modules/x/index.js', '100644', 'blob', 'vendor'],
    ['apps/web/.next/server.js', '100644', 'blob', 'vendor'],
    ['venv/lib/site.py', '100644', 'blob', 'vendor'],
    ['assets/logo.png', '100644', 'blob', 'binary'],
    ['public/app.min.js', '100644', 'blob', 'minified'],
    ['link', '120000', 'blob', 'symlink'],
    ['third_party/lib', '160000', 'commit', 'submodule'],
    ['src/a.ts', '100644', 'blob', null],
  ] as const)('%s → %s', (path, mode, type, reason) => expect(skipReasonForPath(path, mode, type)).toBe(reason));
});

describe('skipReasonForContent', () => {
  const text = (s: string) => Buffer.from(s, 'utf8');

  it('skips too-large files but never lockfiles', () => {
    expect(skipReasonForContent('src/big.ts', 2 * MB, text('x'), MB)).toBe('too_large');
    expect(skipReasonForContent('package-lock.json', 5 * MB, text('{}'), MB)).toBeNull();
  });

  it('detects binary content by NUL bytes', () => {
    expect(skipReasonForContent('data.txt', 10, Buffer.from([0x61, 0x00, 0x62]), MB)).toBe('binary');
  });

  it('detects minified JS/CSS by average line length', () => {
    expect(skipReasonForContent('bundle.js', 5_000, text('a'.repeat(5_000)), MB)).toBe('minified');
    expect(skipReasonForContent('src/a.ts', 5_000, text('const a = 1;\n'.repeat(300)), MB)).toBeNull();
  });

  it('detects generated-file markers in the first lines', () => {
    expect(skipReasonForContent('src/gen.ts', 100, text('// @generated by protoc\nexport {}'), MB)).toBe('generated');
    expect(skipReasonForContent('api.py', 100, text('# Code generated by tool. DO NOT EDIT.\n'), MB)).toBe('generated');
    expect(skipReasonForContent('yarn.lock', 100, text('# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT\n'), MB)).toBeNull();
  });
});
