import { describe, expect, it } from 'vitest';
import { parseLockfile } from '../src/analyzers/dependencies/lockfiles/index';
import type { LockfileRef } from '../src/analyzers/dependencies/lockfiles/discover';

function ref(path = 'yarn.lock', manifestDir = ''): LockfileRef {
  return { path, kind: 'yarn-lock', manifestDir };
}

describe('yarn.lock v1 (classic)', () => {
  const manifest = JSON.stringify({
    name: 'demo',
    dependencies: { 'follow-redirects': '^1.15.0' },
    devDependencies: { mocha: '^10.0.0' },
  });

  const lock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"follow-redirects@^1.15.0":
  version "1.15.2"
  resolved "https://registry.yarnpkg.com/follow-redirects/-/follow-redirects-1.15.2.tgz#abc"
  integrity sha512-xxx

mocha@^10.0.0:
  version "10.2.0"
  resolved "https://registry.yarnpkg.com/mocha/-/mocha-10.2.0.tgz#def"
  dependencies:
    ms "2.1.3"
    "@scope/pkg" "^1.0.0"

ms@2.1.3:
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/ms/-/ms-2.1.3.tgz#ghi"

"@scope/pkg@^1.0.0":
  version "1.2.0"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-1.2.0.tgz#jkl"
`;

  it('resolves specs to the matching entry and computes direct/scope from the sibling package.json', () => {
    const g = parseLockfile(ref(), lock, manifest);
    expect([...g.nodes.keys()].sort()).toEqual(['npm:@scope/pkg@1.2.0', 'npm:follow-redirects@1.15.2', 'npm:mocha@10.2.0', 'npm:ms@2.1.3']);
    expect(g.roots.sort()).toEqual(['npm:follow-redirects@1.15.2', 'npm:mocha@10.2.0']);
    expect(g.nodes.get('npm:follow-redirects@1.15.2')!.scope).toBe('prod');
    expect(g.nodes.get('npm:mocha@10.2.0')!.scope).toBe('dev');
    expect(g.nodes.get('npm:mocha@10.2.0')!.children.sort()).toEqual(['npm:@scope/pkg@1.2.0', 'npm:ms@2.1.3']);
    expect(g.nodes.get('npm:ms@2.1.3')!.scope).toBe('dev');
  });

  it('never throws on malformed/empty content', () => {
    const g = parseLockfile(ref(), '');
    expect(g.nodes.size).toBe(0);
  });

  it('without a sibling package.json, falls back to treating every package as a direct prod dep', () => {
    const g = parseLockfile(ref(), lock);
    expect(g.warnings.some((w) => w.includes('no sibling package.json'))).toBe(true);
    expect(g.roots.length).toBe(4);
  });
});

describe('yarn.lock (Berry)', () => {
  const manifest = JSON.stringify({
    name: 'demo',
    dependencies: { lodash: '^4.17.21' },
  });

  const lock = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: abc
  languageName: node
  linkType: hard

"has-flag@npm:^4.0.0, has-flag@npm:~4.0.0":
  version: 4.0.0
  resolution: "has-flag@npm:4.0.0"
  languageName: node
  linkType: hard

"supports-color@npm:^8.1.1":
  version: 8.1.1
  resolution: "supports-color@npm:8.1.1"
  dependencies:
    has-flag: "npm:^4.0.0"
  languageName: node
  linkType: hard
`;

  it('parses npm: protocol specs and resolves dependency ranges across header variants', () => {
    const g = parseLockfile(ref(), lock, manifest);
    expect([...g.nodes.keys()].sort()).toEqual(['npm:has-flag@4.0.0', 'npm:lodash@4.17.21', 'npm:supports-color@8.1.1']);
    expect(g.nodes.get('npm:supports-color@8.1.1')!.children).toEqual(['npm:has-flag@4.0.0']);
    expect(g.roots).toEqual(['npm:lodash@4.17.21']);
    expect(g.nodes.get('npm:lodash@4.17.21')!.scope).toBe('prod');
    expect(g.nodes.get('npm:supports-color@8.1.1')!.scope).toBe('dev'); // not reachable from the one prod root
  });

  it('never throws on malformed YAML', () => {
    const g = parseLockfile(ref(), '__metadata:\n  version: [unterminated');
    expect(g.nodes.size).toBe(0);
    expect(g.warnings.length).toBeGreaterThan(0);
  });
});
