import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { GitService } from '../src/git/GitService';
import { RepoIndexer } from '../src/index/RepoIndexer';
import { createFixtureRepo, type FixtureRepo } from './fixtures/gitRepo';

let repo: FixtureRepo;
let workDir: string;
let git: GitService;
let dir: string;

beforeAll(async () => {
  repo = await createFixtureRepo([{
    files: {
      'package.json': JSON.stringify({ name: 'demo', bin: { demo: './bin/cli.js' }, dependencies: { express: '^4' } }),
      'package-lock.json': '{"lockfileVersion":3}' + ' '.repeat(600),
      'tsconfig.json': '{ "compilerOptions": { "baseUrl": ".", "paths": { "@/*": ["src/*"] } } }',
      'src/server.ts': "import express from 'express';\nimport { db } from '@/db';\nconst app = express();\napp.post('/login', () => {});\n",
      'src/db.ts': "import fs from 'node:fs';\nexport const db = {};\n",
      'src/broken.ts': "import x from './does-not-exist';\n",
      'bin/cli.js': "require('../src/db');\n",
      'app/api/users/route.ts': 'export async function GET() {}\n',
      'api/main.py': "from flask import Flask\nfrom .helpers import util\napp = Flask(__name__)\n@app.route('/health')\ndef health(): return 'ok'\n",
      'api/__init__.py': '',
      'api/helpers/__init__.py': '',
      'api/helpers/util.py': 'import yaml\n',
      'node_modules/left-pad/index.js': 'module.exports = 1;\n',
      'public/vendor.min.js': 'var a=1;',
      'assets/logo.png': 'not really a png',
      'src/huge.ts': `export const big = "${'x'.repeat(2_000)}";\n`,
      'src/gen.ts': '// @generated by codegen\nexport {};\n',
      'tests/server.test.ts': "import '../src/server';\n",
    },
    symlinks: { 'src/link.ts': '../../etc/passwd' },
  }]);
  workDir = await mkdtemp(join(tmpdir(), 'vibesec-idx-'));
  git = new GitService({ workDir, cloneTimeoutMs: 60_000, stallMs: 20_000, allowFileProtocol: true });
  await git.init();
  dir = await git.ensureCheckout('idx', repo.url, repo.shas[0]!);
}, 60_000);

afterAll(async () => {
  await repo.cleanup();
  await rm(workDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
});

describe('RepoIndexer', () => {
  it('classifies, skips, resolves imports and finds entrypoints', async () => {
    const touches: number[] = [];
    const indexer = new RepoIndexer(git, { maxFiles: 1_000, maxFileBytes: 1_024 });
    const index = await indexer.index(dir, repo.shas[0]!, { touch: () => touches.push(1) });
    const file = (p: string) => index.files.find((f) => f.path === p)!;

    expect(file('node_modules/left-pad/index.js').skipReason).toBe('vendor');
    expect(file('public/vendor.min.js').skipReason).toBe('minified');
    expect(file('assets/logo.png').skipReason).toBe('binary');
    expect(file('src/huge.ts').skipReason).toBe('too_large');
    expect(file('src/gen.ts').skipReason).toBe('generated');
    expect(file('src/link.ts').skipReason).toBe('symlink');
    expect(file('package-lock.json')).toMatchObject({ category: 'lockfile', skipReason: null });
    expect(file('tests/server.test.ts').tags).toContain('test');
    expect(file('src/server.ts').blobSha).toMatch(/^[0-9a-f]{40}$/);

    const edge = (from: string, spec: string) => index.imports.find((e) => e.from === from && e.specifier === spec);
    expect(edge('src/server.ts', 'express')).toMatchObject({ kind: 'package', pkg: 'express', line: 1 });
    expect(edge('src/server.ts', '@/db')).toMatchObject({ kind: 'local', to: 'src/db.ts', line: 2 });
    expect(edge('src/db.ts', 'node:fs')).toMatchObject({ kind: 'builtin' });
    expect(edge('src/broken.ts', './does-not-exist')).toMatchObject({ kind: 'unresolved' });
    expect(edge('bin/cli.js', '../src/db')).toMatchObject({ kind: 'local', to: 'src/db.ts' });
    expect(edge('api/main.py', 'flask')).toMatchObject({ kind: 'package', pkg: 'flask' });
    expect(edge('api/main.py', '.helpers.util')).toMatchObject({ kind: 'local', to: 'api/helpers/util.py' });
    expect(edge('api/helpers/util.py', 'yaml')).toMatchObject({ kind: 'package', pkg: 'pyyaml' });
    expect(index.imports.some((e) => e.from.startsWith('node_modules/'))).toBe(false);

    const kinds = index.entrypoints.map((e) => `${e.kind}:${e.path}`);
    expect(kinds).toEqual(expect.arrayContaining([
      'http-route:src/server.ts', 'next-route:app/api/users/route.ts', 'http-route:api/main.py', 'cli:bin/cli.js',
    ]));

    expect(index.stats).toMatchObject({ totalFiles: index.files.length, truncated: false });
    expect(index.stats.skipped).toMatchObject({ vendor: 1, minified: 1, binary: 1, too_large: 1, generated: 1, symlink: 1 });
    expect(index.stats.byLanguage.typescript).toBeGreaterThan(0);
    expect(touches.length).toBeGreaterThan(0);
  }, 60_000);

  it('marks files beyond maxFiles as file_limit, but never lockfiles', async () => {
    const indexer = new RepoIndexer(git, { maxFiles: 3, maxFileBytes: 1_024 });
    const index = await indexer.index(dir, repo.shas[0]!);
    expect(index.stats.truncated).toBe(true);
    expect(index.stats.skipped.file_limit).toBeGreaterThan(0);
    expect(index.files.find((f) => f.path === 'package-lock.json')?.skipReason).toBeNull();
  }, 60_000);

  it('stops when the signal is aborted', async () => {
    const ac = new AbortController();
    ac.abort();
    await expect(new RepoIndexer(git, { maxFiles: 10, maxFileBytes: 1_024 }).index(dir, repo.shas[0]!, { signal: ac.signal }))
      .rejects.toMatchObject({ code: 'CANCELLED' });
  });
});
